# Generated by Django 5.2.17 on 2026-09-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('filial', models.IntegerField()),
                ('codigo_cliente', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=120)),
                ('documento_cliente', models.CharField(max_length=30)),
                ('implantador', models.CharField(max_length=120)),
                ('data_implantacao', models.DateField(blank=True, null=True)),
                ('prazo_implementacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'implantacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modulos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaImplantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('bloqueada', 'Bloqueada')], default='pendente', max_length=30)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('implantacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='implantacao.implantacao')),
            ],
            options={
                'db_table': 'implantacoes_etapas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ImplantacaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('implantacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='implantacao.implantacao')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implantacoes', to='implantacao.modulo')),
            ],
            options={
                'db_table': 'implantacoes_modulos',
            },
        ),
        migrations.CreateModel(
            name='OrigemMovidesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.BigIntegerField(unique=True)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('dados_origem', models.JSONField(default=dict)),
                ('implantacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movidesk', to='implantacao.implantacao')),
            ],
            options={
                'db_table': 'implantacoes_origens_movidesk',
            },
        ),
        migrations.CreateModel(
            name='TarefaImplantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='implantacao.etapaimplantacao')),
            ],
            options={
                'db_table': 'implantacoes_tarefas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telas', to='implantacao.modulo')),
            ],
            options={
                'db_table': 'telas',
                'ordering': ['modulo__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImplantacaoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=30)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('implantacao_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='implantacao.implantacaomodulo')),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implantacoes', to='implantacao.tela')),
            ],
            options={
                'db_table': 'implantacoes_telas',
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('implantacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='implantacao.implantacao')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='implantacao.modulo')),
            ],
            options={
                'db_table': 'implantacoes_treinamentos',
                'ordering': ['data_agendada'],
            },
        ),
        migrations.AddConstraint(
            model_name='etapaimplantacao',
            constraint=models.UniqueConstraint(fields=('implantacao', 'ordem'), name='unique_implantacao_etapa_ordem'),
        ),
        migrations.AddConstraint(
            model_name='implantacaomodulo',
            constraint=models.UniqueConstraint(fields=('implantacao', 'modulo'), name='unique_implantacao_modulo'),
        ),
        migrations.AddConstraint(
            model_name='tela',
            constraint=models.UniqueConstraint(fields=('modulo', 'codigo'), name='unique_tela_modulo_codigo'),
        ),
        migrations.AddConstraint(
            model_name='implantacaotela',
            constraint=models.UniqueConstraint(fields=('implantacao_modulo', 'tela'), name='unique_implantacao_tela'),
        ),
    ]
