# Generated by Django 5.2.7 on 2026-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implantacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefaimplantacao',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='treinamento',
            options={'ordering': ['-data_agendada']},
        ),
        migrations.AddField(
            model_name='treinamento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='titulo',
            field=models.CharField(default='Padrao', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='implantacao',
            name='empresa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='implantacao',
            name='filial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='implantacao',
            name='implantador',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='data_agendada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
