# Generated by Django 5.2.7 on 2026-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implantacao', '0002_alter_tarefaimplantacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implantacaomodulo',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implantacaomodulo',
            name='fim_previsto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implantacaomodulo',
            name='inicio_previsto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
