# Generated by Django 5.2.7 on 2025-12-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('texto', models.CharField(max_length=255)),
                ('opcao_a', models.CharField(max_length=255)),
                ('opcao_b', models.CharField(max_length=255)),
                ('opcao_c', models.CharField(max_length=255)),
                ('opcao_d', models.CharField(max_length=255)),
                ('correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='central_treinamentos.treinamento')),
            ],
            options={
                'unique_together': {('treinamento', 'ordem')},
            },
        ),
    ]
