# Generated by Django 5.2.7 on 2026-04-24 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='central_web.modulo')),
                ('usuario_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['id'],
            },
        ),
    ]
